### ISSUE TITLE
MySQL Gateway very slow

### ISSUE THREAD

**Issue by benvogan** [implydata/plyql#48]
This may be user error, but I am finding the performance exceedingly slow (orders of magnitude slower than talking to Druid directly).

Running the following SQL:
select __time, sum(count) from business_events_test where event_type = 'walkin' group by __time

Took 1 minute 55 seconds to run.

Running:
select __time, count from business_events_test where event_type = 'walkin';

Never returned (at least not within the 30 minutes that I let it run).

Running the following Druid query took 3s (note I only have a week's worth of data so the interval doesn't make any difference):

{
  "dimensions": [], 
  "aggregations": [
    {
      "type": "count", 
      "name": "count"
    }
  ], 
  "filter": {
    "type": "selector", 
    "dimension": "event_type", 
    "value": "walkin"
  }, 
  "intervals": "2016-06-27T21:29:15+00:00/2016-07-04T21:29:15+00:00", 
  "limitSpec": {
    "limit": 50000, 
    "type": "default", 
    "columns": [
      {
        "direction": "descending", 
        "dimension": "count"
      }
    ]
  }, 
  "granularity": {
    "duration": 60000.0, 
    "type": "duration"
  }, 
  "postAggregations": [], 
  "queryType": "groupBy", 
  "dataSource": "business_events_test"
}

Edit:
I discovered that writing the query a different way results in fast results:

select count() from business_events_test where event_type = 'walkin' group by TIME_BUCKET(__time, PT1M, "Etc/UTC")

Returns in under 1s.  I don't understand how this is different than the queries above.  The data was ingested with a query granularity of 1 minute so the time bucket function shouldn't actually be doing anything.

The issue I have with this query is that when using TIME_BUCKET the date always appears as the first column in the results.  I tried re-writing as:

select count(), TIME_BUCKET(__time, PT1M, "Etc/UTC") from business_events_test where event_type = 'walkin' group by 2

But the order of the columns does not change.

**Comment by vogievetsky** [comment]
Hi Ben, PlyQL does add some overhead vs talking to Druid directly but it should be reasonably small, on the order of 10%. Certainly not "orders of magnitude".

Whenever you have a PlyQL query that is slow it is possible that it is not being translated into an adequate Druid query ether due to an error in PlyQL or because you actually meant a different query. It is very helpful for debugging if for a given PlyQL query you could run PlyLQ with the `--verbose` flag to see that kind of Druid query will be generated under the hood.

The query `select __time, sum(count) from business_events_test where event_type = 'walkin' group by __time` looks like it would generate a Druid query with `granularity: 'none'` i.e. treat every distinct time point as it's own group. It should not be much slower than `select count() from business_events_test where event_type = 'walkin' group by TIME_BUCKET(__time, PT1M, "Etc/UTC")` if your data is as you have described. I will look into this.

`select __time, count from business_events_test where event_type = 'walkin';` is a query that essentially selects every row of your data where event_type is walkin. Under the hood Plywood is probably busy paginating the the results and studiously downloading them. There is no comparable Druid query as a Druid `select` must take a limit. This query is not going to perform fast and might run out of memory and crash after a while.

As for the order of the columns in a GROUP BY query, it is a know issue and will be fixed.

**Comment by vogievetsky** [comment]
ok yeah, just chatted to the Druids and turns out that `granularity: 'none'` has a ton of overhead in Druid. Right now PlyQL does not know that your data is actually bucketed by minute (it will come Druid 0.9.2) so it can not magically substitute a group by on `__time` with one on `TIME_FLOOR(__time, PT1M, "Etc/UTC")` but one day it will :-)

**Comment by davidagee** [comment]
Please note that this project is now deprecated. Please see the [Druid SQL docs](http://druid.incubator.apache.org/docs/latest/querying/sql) for information on using SQL syntax with Druid.
