### ISSUE TITLE
unsupported part in timeBucket expression error when Order By included

### ISSUE THREAD

**Issue by smountain** [implydata/plyql#6]
I've run into an issue when where arbitrary duration in timeBucket will not work when ORDER BY is included.

`SELECT sum(value), pop, description FROM datasource WHERE description CONTAINS 'stuff' AND pop REGEXP '(abc01)' AND '2016-01-29T18:00:00.000Z' <= __time AND __time < '2016-01-29T19:00:00.000Z' GROUP BY TIME_BUCKET(__time, PT10M, 'Etc/UTC'), pop, description` returns results along with any other arbitrary ISO8601 duration (PT3M, PT10H, etc.)

`SELECT sum(value), pop, description FROM datasource WHERE description CONTAINS 'stuff' AND pop REGEXP '(abc01)' AND '2016-01-29T18:00:00.000Z' <= __time AND __time < '2016-01-29T19:00:00.000Z' GROUP BY TIME_BUCKET(__time, PT10M, 'Etc/UTC'), pop, description ORDER BY pop DESC` does not work and returns `There was an error getting the data: unsupported part in timeBucket expression PT10M` 

Durations listed here https://github.com/implydata/plywood/blob/79ac318e96611d760d284e9e0ef3e58a930dfa6e/src/external/druidExternal.ts#L40 work though. 

Is there a reason durations are checked with ORDER BY and not other queries? I'd prefer to be able to use ORDER BY and send arbitrary durations.

Thanks!

**Comment by vogievetsky** [comment]
Investigating...

**Comment by vogievetsky** [comment]
So that you have found is exactly as it is right now.
There are two ways to do bucketing by time in Druid:
1. Using the granularity spec: faster, can handle any period
2. Using the timeFormat dimension extractionFn: slower, very limited to the allowed periods (i.e. the code you linked)

Right now if you run a GroupBy query that includes grouping on time the sorting is all messed up, this is a bug in Druid.

See:  https://github.com/implydata/plywood/blob/79ac318e96611d760d284e9e0ef3e58a930dfa6e/src/external/druidExternal.ts#L1117

I made this issue https://github.com/druid-io/druid/issues/1926 (that I would appreciate a +1 on)

It is being fixed in this, open PR: https://github.com/druid-io/druid/pull/2032

Now that I think of it, I could handle your query (considering it does not have a LIMIT) in Plywood by using the granularity and sorting the results on the Plywood end. I was hoping not to bother with this, and wait for it to be fixed in Druid.

**Comment by smountain** [comment]
Thanks for investigating. Whatever approach you think is best. It is not critical to include ORDER BY with arbitrary timestamps but it would be nice to have.

**Comment by vogievetsky** [comment]
This is fixed in the latest version of PlyQL 0.7.14
